micronaut:
  application:
    name: keyManagerRest

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: keycloak
    password: password
    schema-generate: CREATE_DROP
jpa.default.properties.hibernate.hbm2ddl.auto: update

jackson:
  serialization:
    writeDateAsTimestamps: false

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keyManager:
      address: 'localhost:50051'

